# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               JB's Factory
tagline:             'Backend dev'
description:         '웹개발자 JB입니다.<br>배운것들을 안잊어버리기 위해 쓰는 블로그 입니다.<br><a href="https://hajaebong.github.io/" target="_blank">@JB</a>.'
url:                 https://hajaebong.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jaebong,Ha
  url:               https://hajaebong.github.io/
  email:             jb9245@betree.co.kr

# Custom vars
version:             1.0.0

# url
category_dir: category/
tag_dir: tag/

# gem 설정을 추가
plugins: ['jekyll-paginate']

# 요약문 구분자
excerpt_seperator:  <!--break-->
